const mongoose = require('mongoose');

const ideaSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  title: { type: String, required: true },
  platform: { type: String },
  type: { type: String },
  hook: { type: String },
  angle: { type: String },
  category: { type: String },
  description: { type: String },
  tags: [String],
  createdAt: { type: Date, default: Date.now }
}, { strict: false }); // 🔥 Allow any other fields generated by AI

module.exports = mongoose.model('Idea', ideaSchema);
