import { useNavigate } from "react-router-dom";
import {
  Copy,
  Trash2,
  Sparkles,
  Camera,
  Briefcase,
  PlayCircle,
  Lightbulb,
} from "lucide-react";
import { toast } from "sonner";

const SavedIdeaCard = ({ idea, onRemove, onExpand }) => {
  const navigate = useNavigate();

  const handleCopy = () => {
    navigator.clipboard.writeText(`${idea.title}\n\n${idea.description || idea.hook}`);
    toast.success("Idea copied to clipboard!");
  };

  const getPlatformIcon = (platform) => {
    const p = (platform || "").toLowerCase();
    if (p.includes("instagram")) return <Camera className="w-4 h-4" />;
    if (p.includes("youtube")) return <PlayCircle className="w-4 h-4" />;
    if (p.includes("linkedin")) return <Briefcase className="w-4 h-4" />;
    return <Lightbulb className="w-4 h-4" />;
  };

  const getPlatformColor = (platform) => {
    const p = (platform || "").toLowerCase();
    if (p.includes("instagram")) return "rgba(236,72,153,0.1) text-pink-400 border-pink-500/20";
    if (p.includes("youtube")) return "rgba(239,68,68,0.1) text-red-400 border-red-500/20";
    if (p.includes("linkedin")) return "rgba(37,99,235,0.1) text-blue-400 border-blue-500/20";
    return "rgba(249,115,22,0.1) text-orange-400 border-orange-500/20";
  };

  if (!idea) return null;

  return (
    <div className="group relative flex flex-col rounded-[32px] border border-[var(--app-border)] bg-[var(--card-bg)] p-6 shadow-sm transition-all duration-300 hover:border-orange-500/30 hover:shadow-xl hover:-translate-y-1">
      <div className="mb-5 flex items-center justify-between">
        <span
          className={`inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-[10px] font-bold uppercase tracking-wider ${getPlatformColor(
            idea.platform
          )}`}
        >
          {getPlatformIcon(idea.platform)}
          {idea.platform || "Thinking"}
        </span>

        <button 
          onClick={() => onRemove && onRemove(idea._id)}
          className="rounded-xl p-2 transition-all hover:bg-red-500/10 hover:text-red-400 group-hover:opacity-100"
          style={{ color: "var(--muted-text)", opacity: 0 }}
        >
          <Trash2 size={16} />
        </button>
      </div>

      <h3 className="text-xl font-black leading-tight text-[var(--app-text)]">
        {idea.title}
      </h3>

      <div className="mt-4 flex-1">
        <p className="line-clamp-3 text-sm leading-relaxed text-[var(--muted-text)]">
          {idea.description || idea.hook || "A high-impact content concept generated by PlanMyContent AI."}
        </p>
      </div>

      <div className="mt-8 flex items-center gap-2 border-t border-[var(--app-border)] pt-6">
        <button 
          onClick={handleCopy}
          className="flex h-11 w-11 items-center justify-center rounded-2xl border border-[var(--app-border)] bg-[var(--card-bg)] text-[var(--muted-text)] transition-all hover:border-orange-500/30 hover:text-orange-500"
          title="Copy to clipboard"
        >
          <Copy size={16} />
        </button>

        <button 
          onClick={onExpand}
          className="flex flex-1 items-center justify-center gap-2 rounded-2xl bg-orange-500 py-3 text-xs font-black text-white shadow-lg shadow-orange-500/20 transition-all hover:bg-orange-600"
        >
          <Sparkles size={14} />
          Expand Strategy
        </button>
      </div>
    </div>
  );
};


export default SavedIdeaCard;